spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      # 以下两句为自定义健康检查请求url
      #discovery:
       # health-check-url:
  application:
    name: spring-cloud-consul
server:
  port: 9999