server:
  port: 8763
spring:
  profiles:
    active: dev
  application:
    name: consul-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-provider